export type AcademicYear = {
  id: string;
  school_id: string;
  name: string;
  slug: string;
  session_type: string;
  session_type_label: string;
  starts_on: string;
  ends_on: string;
  status: string;
  is_default_for_enrolment: boolean;
  generated_from_year_id: string | null;
  approved_at: string | null;
  is_draft: boolean;
  terms: {
    id: string;
    school_id: string;
    academic_year_id: string;
    name: string;
    slug: string;
    sequence: number;
    starts_on: string;
    ends_on: string;
    status: string;
    created_at: string;
    updated_at: string;
  }[];
  created_at: string;
  updated_at: string;
};
