import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Poppins,
  Lora,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { Footer } from "./_components";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        poppins.variable,
        lora.variable,
        "font-mono",
        jetbrainsMono.variable
      )}
    >
      <body className="min-h-full">
        <Providers>
          <div className="mx-auto flex flex-col max-w-360 min-h-full">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
