"use client";
import { useState } from "react";
import { Text } from "@/components/ui";
import { Button } from "@/components/ui/custom-button";
import Image from "next/image";
import OTP from "@/components/ui/custom-otp-input";

const options = [
  {
    title: "Authenticator App",
    id: "app",
  },
  {
    title: "Email OTP",
    id: "email",
  },
  {
    title: "SMS OTP",
    id: "sms",
  },
];
export default function Authenticator() {
  const [active, setActive] = useState<null | string>(null);
  const [code, setCode] = useState("null");
  return (
    <section>
      <div className="flex flex-col gap-6 mb-12">
        <div className="text-left">
          <Text
            scale={"feature"}
            weight={"bold"}
            className="text-neutrals-1000 mb-2"
          >
            Set up MFA
          </Text>
          <Text scale={"content"} className="font-normal text-neutral-900">
            Kindly follow these steps to set up your Multi Factor Authentication
          </Text>
        </div>

        <ol className="list-decimal pl-6 space-y-2">
          <li>
            <Text scale={"highlight"} weight={"standard"}>
              Install an authenticator app like Google Authenticator
            </Text>
          </li>
          <li>
            <Text
              scale={"highlight"}
              weight={"standard"}
            >{`Scan the QR code below with your authenticator app or enter the text code (${code}) on the authenticator app`}</Text>
            <Image
              src={"/"}
              width={179}
              height={179}
              alt="qr-code"
              className="justify-self-center my-6"
            />
          </li>
          <li>
            <Text scale={"highlight"} weight={"standard"}>
              Enter the OTP generated by the app and click enable
            </Text>
          </li>
        </ol>
      </div>

      <OTP length={6} className="mb-6 justify-self-center" />

      <div className="flex gap-6 justify-between items-center">
        <Button variant="secondary" size="lg" className="min-w-0 flex-1">
          Cancel
        </Button>
        <Button size="lg" className="min-w-0 flex-1">
          Enable
        </Button>
      </div>
    </section>
  );
}
