import { Text } from "@/components/ui";
import Image from "next/image";
import Form from "./form";
import { authenticatorSetup } from "@/features/auth/api/mfa";

export default async function Authenticator() {
  //const res = await authenticatorSetup();
  return (
    <section>
      <div className="flex flex-col gap-6 mb-12">
        <div className="text-left">
          <Text
            scale={"feature"}
            weight={"bold"}
            className="text-neutrals-1000 mb-2"
          >
            Set up MFA
          </Text>
          <Text scale={"content"} className="font-normal text-neutral-900">
            Kindly follow these steps to set up your Multi Factor Authentication
          </Text>
        </div>

        <ol className="list-decimal pl-6 space-y-2">
          <li>
            <Text scale={"highlight"} weight={"standard"}>
              Install an authenticator app like Google Authenticator
            </Text>
          </li>
          <li>
            <Text
              scale={"highlight"}
              weight={"standard"}
            >{`Scan the QR code below with your authenticator app or enter the text code (${""}) on the authenticator app`}</Text>
            <Image
              src={"/"}
              width={179}
              height={179}
              alt="qr-code"
              className="justify-self-center my-6"
            />
          </li>
          <li>
            <Text scale={"highlight"} weight={"standard"}>
              Enter the OTP generated by the app and click enable
            </Text>
          </li>
        </ol>
      </div>

      <Form />
    </section>
  );
}
